[package]
name = "rs-phf"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
"rs-token" = { path = "../rs-token" }
"phf" = { version = "0.11.1", features = ["macros"] }
